### ISSUE TITLE
Update Readme.md/addon's UI labels to include Windows users' default keymapping translation

### ISSUE THREAD

**Issue by CollinChaffin** [turigeza/fold-navigator#10]
Hi Geza!

So, I did some additional testing using the default installation settings that include the default hotkeys with the intent that, based on #4 of your "Notes" section of the readme, I would have to change them as I am a Windows user and since we don't have the "command" key that in your testing the defaults would not work. 

Well, I actually have some great news for you!  In my testing over the years, and once again now with your Atom package, I can confirm that a seemingly still relatively little-known secret is that the WINDOWS key replaces the Mac's CMD key.  So, you can update your #4 to simply indicate that Windows users can literally use all the predefined key-mappings and to simply substitute the WIN key for CMD and they will all work just fine.  My initial first open of the fold-nav pane worked great using "CTRL-ALT-WIN-[" as do all subsequent toggles! :)

Of note, even though I am a WIN user, regardless of the host OS, all the default key-mappings were enabled upon installation but labeled with all the MAC specific keys (ie. "CTRL-ALT-CMD-UP").  So, even though I opened this ticket to report good news, technically both the readme.md and the addon's UI labels showing the definitions could be updated to reflect this OS variation to help eliminate any confusion.

Hope this helps a bit.  Again, awesome addon!

Collin

**Comment by turigeza** [comment]
Hi Collin,

Thank you for letting me know about it. :) Good news indeed. It didn't used to work and when I switched my Windows machine on and tried it, it would NOT work. 

Only after upgrading Atom to the latest it started to work. So it might be related to the Atom version I tried it on.

I will update the readme later.

Thanks again 👍
