### ISSUE TITLE
folded every line in code

### ISSUE THREAD

**Issue by Julius-Nepos** [turigeza/fold-navigator#15]
Just loaded the fold-Navigator.  According to instructions I'm supposed to do a CTRL-ALT-WinKey-[ to activate it.  I did this and it created maybe 200 folds in my code.  Every command is folded up.   To see anything I have to go thru maybe 200 unfoldings.  I wish somehow it didn't automatically fold up every command.

OF COURSE there is nothing in any doc on how to UNFOLD.  There are no unfold commands listed in the documentation.  Everything for folding, nothing for unfolding.   I guess the folding is a trap, one way only?

Stuff like this is why people delete these apps.   Maybe make it somewhat user friendly?

**Comment by turigeza** [comment]
This is just moaning. Nothing constructive in here.

You are right now this plugin is not for the public anymore and I will remove it eventually when I get a chance. Having said that I use it all the time and suit my needs. 

Here is a screenshot of the menu items you could have used. 

<img width="527" alt="Screen Shot 2020-12-20 at 21 51 14" src="https://user-images.githubusercontent.com/9335740/102725357-09ec0d00-430e-11eb-9cfa-d79e8767c0ab.png">

**Comment by Julius-Nepos** [comment]
closed?  Really helpful view of support.  How does one get to those menus?  They weren't available for my install.
