### ISSUE TITLE
Feature Request: Context menu option to close Fold Navigator

### ISSUE THREAD

**Issue by DamnedScholar** [turigeza/fold-navigator#3]
I see the context menu option to open Fold Navigator, which is great, but there should probably be a companion option to close the pane, probably replacing the open entry on the main context menu and definitely when right-clicking over the Fold Navigator pane. As it is, it requires a dedicated keybinding or going into the `Packages` menu to close it once you're done.

**Comment by turigeza** [comment]
Hey,

You are right. I have changed everything to toggle now instead of open/close. And also provided a context menu just with one option close panel over the fold navigator panel as you suggested. 

Hope it helps let me know.

Geza

**Comment by DamnedScholar** [comment]
Perfect. :smiley:
