### ISSUE TITLE
Configure the plugin

### ISSUE THREAD

**Issue by sylvan-d-ash** [turigeza/fold-navigator#5]
I think you forgot to add an example of how to configure the plugin. In particular, I'd like to know how to limit the depth to 1. Cheers

**Comment by turigeza** [comment]
Hi,

You configure this plugin just like any other. I didn't think I would need to add an example for that : )) But basically :

Atom -> Preferences > Packages 
![screen shot 2016-07-14 at 13 21 04](https://cloud.githubusercontent.com/assets/9335740/16839261/1b962108-49c6-11e6-8d22-afa16570d2ef.png)

Search for "fold-" it and fold navigator is within the list. Click "settings"
![screen shot 2016-07-14 at 13 21 19](https://cloud.githubusercontent.com/assets/9335740/16839265/23eeb0d6-49c6-11e6-9905-6b16364d3a2f.png)

"Maximum fold level" it is called and all the other settings are there.
![screen shot 2016-07-14 at 13 22 00](https://cloud.githubusercontent.com/assets/9335740/16839302/4c0deffa-49c6-11e6-9e8d-0066ecf00fdd.png)

If you want to do it per language bases you need to follow the link in here https://github.com/turigeza/fold-navigator#8-per-languagegrammar-settings

Again this is not limited to my plugin.

My config cson looks like this : 

```
"*":
  "atom-beautify":
    general:
      _analyticsUserId: "895a328f-d3a2-46a3-b5e6-1c2450b87c5b"
  core:
    disabledPackages: [
      "php-class-tree"
      "php-integrator-base"
      "php-integrator-navigation"
      "php-integrator-symbol-viewer"
      "minimap-highlight-selected"
      "minimap"
      "git-control"
      "linter-htmlhint"
      "linter-js-standard"
      "fold-functions"
      "linter-phpcs"
      "linter-jshint"
    ]
    packagesWithKeymapsDisabled: []
    themes: [
      "one-dark-ui"
      "atom-dark-syntax"
    ]
  editor:
    fontSize: 13
    invisibles: {}
    showIndentGuide: true
    softWrap: true
    tabLength: 4
  "exception-reporting":
    userId: "ec8c1966-0ee8-dead-006f-c6f57b6493b4"
  "fold-functions":
    autofold: true
    autofoldGrammars: []
    shortfileCutoff: 42
  "fold-navigator":
    maxFoldLevel: 3
  "linter-jshint":
    lintInlineJavaScript: true
  minimap:
    absoluteMode: true
    plugins:
      "highlight-selected": true
      "highlight-selectedDecorationsZIndex": 0
  "one-dark-ui": {}
  "project-plus":
    autoDiscover: false
  "split-diff":
    diffWords: true
    ignoreWhitespace: true
    leftEditorColor: "red"
    rightEditorColor: "green"
    syncHorizontalScroll: true
  welcome:
    showOnStartup: false
".html.php.text":
  "fold-navigator":
    indentationCharacter: "-"
    maxFoldLevel: 1
".js.jsx.source":
  "fold-navigator":
    indentationCharacter: "-"
```

**Comment by sylvan-d-ash** [comment]
hmm...couldn't (and still can't) see the Settings option for the plugin, that's why I asked. But it could be because I didn't restart Atom after installing it. Let me restart it first

**Comment by turigeza** [comment]
How did you get on ... ? Send me a screenshot of the settings page when you are searching for the plugin if you can. See if I can spot anything. 

You only have problem with this particular plugin and no other ones?

How did you install it ? Command line ?

**Comment by sylvan-d-ash** [comment]
I just needed to restart Atom. Everything worked OK after that. Nice plugin and thanks for the quick response
