### ISSUE TITLE
need open with Atom configuration

### ISSUE THREAD

**Issue by WindieChai** [turigeza/fold-navigator#6]
Hi,
Please add a configuration option to allow openning fold-navigator automatically after Atom started.

Thanks.

**Comment by turigeza** [comment]
Hey,

I had a go at that and it was not that easy as it sounds some of the vars not available at startup time and code needs rewriting to accommodate that  ... 

So I kept it like this for a reason. This plugin will not load at start but only when you open the panel. Maybe in the distant future I think about that but for now I have to work on something else ... Sorry.

Assign a shortcut for it. It is one push of a button ... the one already assigned (mac) ctrl+alt+cmd+[
This for me works and after all I can not remember when the last time I have restarted atom it must be around 2 weeks now ... 

So maybe in the feature. But not for the next couple of months for sure. 

Geza
