### ISSUE TITLE
navigating through folds opens the fold

### ISSUE THREAD

**Issue by xh3b4sd** [turigeza/fold-navigator#7]
I am a vim user and like atom very much. What is holding me back using it is certain features I use for my workflow. I found your plugin and it is cool. There are only some things I would like to configure. For instance when I move from fold to fold I do not want to open the fold all the time. When I want to open the fold I use a shortcut to do so. Is there a chance to make this work?

**Comment by turigeza** [comment]
I had a quick go at it however 
https://github.com/turigeza/fold-navigator/blob/master/lib/fold-navigator.js#L998

editor.setCursorBufferPosition([row, 0]);
Will not work aka I can not move the cursor into position unless the code is unfolded beforehand.

So there is no easy quick solution. Sorry.
